apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: staff-service
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: position-tracker
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: position-simulator
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vehicle-telemetry
  namespace: default
